# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    timezone: '%env(APP_TIMEZONE)%'
    user_avatar_placeholder: '/images/placeholder.png'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    user.admin:
        class: App\Admin\UserAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\User, manager_type: orm, group: 'Пользователи', label: 'User',  }

    city.admin:
        class: App\Admin\CityAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\City, manager_type: orm, group: 'Города', label: 'City' }

    file.admin:
        class: App\Admin\FileAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\File, manager_type: orm, group: 'Изображения', label: 'File' }
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
